name: my_cab
description: A new Flutter project.
version: 1.0.5+5
environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.5
  smooth_page_indicator: ^1.1.0
  country_pickers: ^2.0.0
  font_awesome_flutter: ^10.4.0
  google_maps_flutter: ^2.2.8
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  provider: ^6.0.3
  fluttertoast: ^8.2.1
  shared_preferences: ^2.1.1
  geolocator: ^10.1.0
  flutter_local_notifications: ^16.1.0
  flutter_ringtone_player: ^4.0.0+2
  http: ^1.1.0
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jsonFile/